on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ '**' ]

# Set default permissions as read only.
permissions: read-all

name: Go
jobs:

  go-test:
    strategy:
      matrix:
        go-version: ['oldstable', 'stable']
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v6
    - name: Install Go
      uses: actions/setup-go@v6
      with:
        go-version: ${{ matrix.go-version }}
    - name: Download Go dependencies
      env:
        GOPROXY: "https://proxy.golang.org"
      run: go mod download
    - name: Compile code
      run: go build .

  code-check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v6
    - name: Install Go
      uses: actions/setup-go@v6
      with:
        go-version-file: go.mod
    - name: lint
      run: |
        make lint
    - name: vulncheck
      run: |
        make vulncheck
    - name: fmt
      run: |
        make fmt
        git diff --exit-code
